// Language translations
const translations = {
    en: {
        "about-title": "About Us",
        "about-description": "We are a group of students who take part in different projects at the university. We help other students as Teaching Assistants in Lab Sessions, we contribute to the current research going on at the university, and support the community work that is done to interest more people in computer science and programming.",
        "about-hero-eyebrow": "Behind the Tutorial Education Program",
        "about-hero-list-1": "Teaching labs & mentoring support",
        "about-hero-list-2": "Outreach events across the university",
        "about-hero-list-3": "Outreach events across Sweden",
        "header-projects": "Projects",
        "header-events": "Events",
        "header-aboutUs": "About Us",
        "header-english": "English",
        "header-swedish": "Swedish",
        "hero-eyebrow": "Tutorial Education Program",
        "hero-heading": "Make an impact while you study.",
        "hero-cta-primary": "Meet the team",
        "hero-cta-secondary": "Explore current projects",
        "hero-highlight-eyebrow": "Right now at TEP",
        "hero-stat-projects-label": "Running projects",
        "hero-stat-projects-sub": "Updated weekly",
        "hero-stat-events-label": "Upcoming events",
        "hero-stat-events-sub": "Across Växjö & Kalmar",
        "hero-next-event-eyebrow": "Next on our calendar",
        "TEP-description": "Discover flexible roles that blend teaching support, research practice, and outreach while you study at Linnaeus University.",
        "projects-hero-eyebrow": "Projects & Initiatives",
        "projects-hero-heading": "Student-built solutions across LNU.",
        "projects-hero-lead": "Explore how Tutorial Education Program teams support labs, research pilots, and outreach experiences every term.",
        "projects-hero-cta-primary": "Browse active projects",
        "projects-hero-cta-secondary": "Pitch a new idea",
        "projects-hero-stat-active-label": "Active projects",
        "projects-hero-stat-active-sub": "Collaborations this term",
        "projects-hero-stat-members-label": "Students involved",
        "projects-hero-stat-members-sub": "Across Växjö & Kalmar",
        "projects-hero-latest-label": "Latest kickoff",
        "projects-hero-pill-label": "Focus areas",
        "projects-library-eyebrow": "Project Library",
        "projects-library-title": "Browse every initiative",
        "projects-library-description": "Sorted from most recent. Tap a card to open the detail page, meet the team, and explore the outcomes.",
        "events-title": "Events & Outreach",
        "events-lead": "Explore community outreach, open houses, and programming activities where TEP students make an impact.",
        "events-instructions": "Click or tap a tile to open the event page.",
        "event-status-completed": "Completed",
        "team-title": "Our Team",
        "team-description": "Our team consists of students from around the world studying various programs at LNU.",
        "team-alumni-title": "Alumni",
        "team-alumni-description": "Former TEP members who continue to make an impact beyond the programme.",
        "team-alumni-badge": "Alumni",
        "team-empty-current": "No active members to show right now.",
        "team-empty-alumni": "Alumni will be listed soon.",
        "member1-name": "Member 1",
        "member1-info": "Program name, year of studies",
        "member1-quote": "Here I am writing in English!",
        "member1-projects": [
        { name: "Project A", link: "#" },
        { name: "Project B", link: "#" }
        ],
        "member2-name": "Member 2",
        "member2-info": "Program name, year of studies",
        "member2-quote": "Here I am writing in English!",
        "member2-projects": [
        { name: "Project A", link: "#" },
        { name: "Project B", link: "#" }
        ],
        "member3-name": "Member 3",
        "member3-info": "Program name, year of studies",
        "member3-quote": "Here I am writing in English!",
        "member3-projects": [
        { name: "Project A", link: "#" },
        { name: "Project B", link: "#" }
        ],
        "member4-name": "Member 4",
        "member4-info": "Program name, year of studies",
        "member4-quote": "Here I am writing in English!",
        "member4-projects": [
        { name: "Project A", link: "#" },
        { name: "Project B", link: "#" }
        ],
        "member5-name": "Member 5",
        "member5-info": "Program name, year of studies",
        "member5-quote": "Here I am writing in English!",
        "member5-projects": [
        { name: "Project A", link: "#" },
        { name: "Project B", link: "#" }
        ],
        "member6-name": "Member 6",
        "member6-info": "Program name, year of studies",
        "member6-quote": "Here I am writing in English!",
        "member6-projects": [
        { name: "Project A", link: "#" },
        { name: "Project B", link: "#" }
        ],
        "member7-name": "Member 7",
        "member7-info": "Program name, year of studies",
        "member7-quote": "Here I am writing in English!",
        "member7-projects": [
        { name: "Project A", link: "#" },
        { name: "Project B", link: "#" }
        ],
        "member8-name": "Member 8",
        "member8-info": "Program name, year of studies",
        "member8-quote": "Here I am writing in English!",
        "member8-projects": [
        { name: "Project A", link: "#" },
        { name: "Project B", link: "#" }
        ],
        "mission-title": "Our Mission",
        "mission-description": "TEP empowers students to grow as educators, researchers, and community leaders while contributing to meaningful projects at Linnaeus University.",
        "mission-point-1": "Develop teaching confidence with guided lab support.",
        "mission-point-2": "Explore applied research in collaboration with faculty.",
        "mission-point-3": "Lead outreach that inspires future students.",
        "mission-events-cta": "See upcoming events",
        "what-is-tep-title": "What is TEP?",
        "what-is-tep-description": "The Tutorial Education Program offers flexible, paid roles for students who want to build their CV, strengthen academic skills, and make a campus-wide impact.",
        "what-is-tep-highlight-1": "Structured mentorship and training with experienced staff.",
        "what-is-tep-highlight-2": "Opportunities to connect coursework with real-world projects.",
        "what-is-tep-highlight-3": "Support for both English and Swedish speaking students.",
        "pillars-title": "Our Three Pillars",
        "pillars-description": "Every participant blends core responsibilities across teaching, research, and community work. You can focus on one track or rotate between them based on interest and availability.",
        "pillar-ta-title": "Teaching Assistance",
        "pillar-ta-description": "Guide lab sessions, answer course questions, and help classmates decode complex concepts.",
        "pillar-ta-point-1": "Flexible mentorship hours that fit around your studies.",
        "pillar-ta-point-2": "Real classroom experience with feedback from instructors.",
        "pillar-research-title": "Research Support",
        "pillar-research-description": "Work alongside faculty on active projects—from data analysis to prototyping and documentation.",
        "pillar-research-point-1": "Hands-on practice using academic tools and methods.",
        "pillar-research-point-2": "Co-create results you can proudly showcase in your CV.",
        "pillar-community-title": "Community Outreach",
        "pillar-community-description": "Design events and workshops that invite new voices into computing and celebrate diversity.",
        "pillar-community-point-1": "Collaborate with schools, associations, and local partners.",
        "pillar-community-point-2": "Inspire future students through interactive activities.",
        "community-title": "Ready To Apply?",
        "community-description": "Join the Tutorial Education Program and help us deliver labs, research support, and outreach across Linnaeus University.",
        "community-cta-primary": "Apply now",
        "community-cta-secondary": "View our members",
        "community-requirement-title": "Prerequisites",
        "community-requirement-1": "Enrolled at Linnaeus University.",
        "community-requirement-2": "Second-year bachelor or master’s student in CS or Media Technology.",
        "community-requirement-3": "Curious about teaching, research, or outreach.",
        "community-workload-title": "Choose Your Workload",
        "community-workload-1": "25% part-time (approx. 10 hours/week).",
        "community-workload-2": "50% part-time (approx. 20 hours/week).",
        "community-workload-3": "Schedule tailored around your courses.",
        "community-support-title": "What You’ll Get",
        "community-support-1": "Mentoring from experienced staff.",
        "community-support-2": "Hands-on experience for your CV.",
        "community-support-3": "Access to events, workshops, and project teams.",
        "event-tag-outreach": "Outreach",
        "event-tag-course": "Course",
        "event-tag-career": "Career",
        "event-tag-openhouse": "Open House",
        "event-digitalidag-name": "Digital Day (Digitalidag)",
        "event-digitalidag-datetime": "October 10th · 13.00–17.00",
        "event-digitalidag-location": "Location: Linnaeus University (details coming soon)",
        "event-digitalidag-language": "Languages: Swedish (information in English available)",
        "event-digitalidag-highlights-heading": "Highlights",
        "event-digitalidag-highlight-1": "Nationwide Digitalidag programming with unique sessions hosted by Linnaeus University.",
        "event-digitalidag-highlight-2": "Activities span both campuses and extend into community venues in Kalmar and Växjö.",
        "event-digitalidag-highlight-3": "Focus on cybersecurity, AI, digital transformation, and playful learning for all ages.",
        "event-digitalidag-overview-heading": "Overview",
        "event-digitalidag-overview-1": "Digitalidag is a nationwide theme day filled with digital activities, hands-on workshops, and discussions across Sweden.",
        "event-digitalidag-overview-2": "Linnaeus University contributes with expert talks, interactive labs, and public events for students, families, professionals, and local communities.",
        "event-digitalidag-overview-3": "Sessions cover cybersecurity, AI, digital transformation, and playful learning at Universitetskajen in Kalmar, Växjö campus, Araby Park Arena, and Växjö Stadsbibliotek.",
        "event-digitalidag-activities-heading": "Activities & sessions",
        "event-digitalidag-activity-1": "Cybersecurity panel (Kalmar · Hus Stella) where municipal leaders, industry experts, and LNU IT specialists discuss hacker threats. Featuring Christoffer Carlsson Schött, Niklas Hörling, Louise Östlund, Henrik Ryttergard, Peter Bergehamn, and Pär Igevik.",
        "event-digitalidag-activity-2": "Breakfast meeting “Konkurrenskraft genom digitalisering” (Kalmar Business Lab) with researchers John Jeansson and Krister Bredmar sharing strategies for digital competitiveness.",
        "event-digitalidag-activity-3": "Experiment workshop on Generative AI (Växjö campus) led by Jonas Svensson focusing on AI tools, human–machine interaction, and the project Människa, maskin, samhälle.",
        "event-digitalidag-activity-4": "“Lek och lär” play lab (Araby Park Arena) where children explore digital creativity through playful, hands-on stations.",
        "event-digitalidag-activity-5": "Public lecture on IoT & AI (Växjö Stadsbibliotek) with Jonas Nordqvist illustrating opportunities and challenges of data-driven innovation.",
        "event-digitalidag-schedule-heading": "Key locations",
        "event-digitalidag-schedule-1": "Universitetskajen, Kalmar — cybersecurity panel, business breakfast, and outreach activations.",
        "event-digitalidag-schedule-2": "Växjö campus — experiment workshops on Generative AI plus student-led demos.",
        "event-digitalidag-schedule-3": "Community venues — Araby Park Arena play lab and Växjö Stadsbibliotek public lecture the day before Digitalidag.",
        "event-digitalidag-participation-heading": "Participation & resources",
        "event-digitalidag-participation-1": "Digitalidag is Sweden’s national initiative to strengthen digital participation and knowledge.",
        "event-digitalidag-participation-2": "Linnaeus University contributes every year with a broad cross-campus programme for learners of all ages.",
        "event-digitalidag-participation-3": "More information: Digitalidag at Linnaeus University · Digitalidag Sweden.",
        "event-digitalidag-participation-4": "Latest update: https://lnu.se/mot-linneuniversitetet/aktuellt/nyheter/2024/digitalidag-2024/",
        "event-vera-dagen-name": "VERA Day at Volvo",
        "event-vera-dagen-datetime": "October 16th",
        "event-vera-dagen-location": "Location: Volvo CE, Braås",
        "event-vera-dagen-language": "Languages: Swedish (support in English)",
        "event-vera-dagen-highlights-heading": "Highlights",
        "event-vera-dagen-highlight-1": "Inspirational tech day for 5th-grade pupils focused on creativity and engineering thinking.",
        "event-vera-dagen-highlight-2": "Hosted by Volvo CE in Braås together with participating Linnaeus University students.",
        "event-vera-dagen-highlight-3": "Hands-on sessions exploring safety, innovation, VR demos, and introductory coding.",
        "event-vera-dagen-highlight-4": "Encourages young girls to stay curious about technology and consider future engineering careers.",
        "event-vera-dagen-overview-heading": "Overview",
        "event-vera-dagen-overview-1": "VERA Day at Volvo is an initiative designed to inspire young girls to explore technology, innovation, and engineering.",
        "event-vera-dagen-overview-2": "Volvo CE in Braås welcomes two classes of 5th-grade pupils to learn how engineers think, create, and solve real-world problems.",
        "event-vera-dagen-overview-3": "Two students from Linnaeus University join the Volvo team on-site to help facilitate activities and answer questions.",
        "event-vera-dagen-overview-4": "The day aims to spark early interest in STEM by showing that technology is creative, meaningful, and accessible to everyone.",
        "event-vera-dagen-activities-heading": "Activities & sessions",
        "event-vera-dagen-activity-1": "Innovation challenges such as brainstorming how technology can make traffic safer.",
        "event-vera-dagen-activity-2": "Group problem-solving where pupils present ideas to classmates and compare approaches.",
        "event-vera-dagen-activity-3": "VR demonstrations that let pupils experience engineering concepts virtually.",
        "event-vera-dagen-activity-4": "Introductory coding exercises that highlight logic, creativity, and digital creation.",
        "event-vera-dagen-activity-5": "Tech exploration stations showing how Volvo CE engineers design machinery, safety features, and future mobility.",
        "event-vera-dagen-activity-6": "Sharing session at the end of the day where pupils present their creative solutions.",
        "event-vera-dagen-schedule-heading": "Key locations",
        "event-vera-dagen-schedule-1": "Volvo CE, Braås — engineering facilities and activity rooms used for workshops, VR, and innovation sessions.",
        "event-vera-dagen-participation-heading": "Participation & resources",
        "event-vera-dagen-participation-1": "VERA Day is arranged by Volvo CE to promote early interest in engineering among young pupils, especially girls.",
        "event-vera-dagen-participation-2": "Two Linnaeus University students assist on-site, supporting workshops and guiding discussions. For more info or photos, contact the organizing team.",
        "event-digitala-kompetensdagen-name": "Digital Competence Day",
        "event-digitala-kompetensdagen-datetime": "October 28th · 08.00–16.00",
        "event-digitala-kompetensdagen-location": "Location: Växjö campus · Hus K",
        "event-digitala-kompetensdagen-language": "Languages: Swedish only",
        "event-digitala-kompetensdagen-highlights-heading": "Highlights",
        "event-digitala-kompetensdagen-highlight-1": "Annual conference for educators and school leaders in Kronoberg County.",
        "event-digitala-kompetensdagen-highlight-2": "Focus on digital competence, new tools, pedagogical innovation, and digital transformation.",
        "event-digitala-kompetensdagen-highlight-3": "Co-arranged by AV-Media Region Kronoberg and Linnaeus University on Växjö campus.",
        "event-digitala-kompetensdagen-overview-heading": "Overview",
        "event-digitala-kompetensdagen-overview-1": "Digitala kompetensdagen is a full-day conference designed to strengthen digital competence among the region’s educators and school leaders.",
        "event-digitala-kompetensdagen-overview-2": "Participants receive new ideas, tools, and knowledge while keeping up with the latest developments in digital learning.",
        "event-digitala-kompetensdagen-overview-3": "The 2025 edition takes place on 28 October at Linnaeus University in Växjö, arranged in collaboration with AV-Media Region Kronoberg.",
        "event-digitala-kompetensdagen-activities-heading": "Activities & sessions",
        "event-digitala-kompetensdagen-activity-1": "Presentations and workshops on digital pedagogical tools and digital transformation in schools.",
        "event-digitala-kompetensdagen-activity-2": "Classroom innovation sessions sharing new methods and best practices for digital learning.",
        "event-digitala-kompetensdagen-activity-3": "Facilitated discussions about opportunities, challenges, and future-ready skills.",
        "event-digitala-kompetensdagen-schedule-heading": "Key locations",
        "event-digitala-kompetensdagen-schedule-1": "Växjö campus · Hus K hosts the plenary talks and main sessions.",
        "event-digitala-kompetensdagen-schedule-2": "Surrounding learning spaces on campus accommodate workshops and breakout discussions.",
        "event-digitala-kompetensdagen-participation-heading": "Participation & partners",
        "event-digitala-kompetensdagen-participation-1": "Digitala kompetensdagen is jointly organized by AV-Media Region Kronoberg and Linnaeus University.",
        "event-digitala-kompetensdagen-participation-2": "Programme updates and registration details will be published on the event webpage.",
        "event-digitala-kompetensdagen-participation-3": "Visitor information, including travel tips and campus access, is available online.",
        "event-digitala-kompetensdagen-participation-4": "Learn more: https://lnu.se/mot-linneuniversitetet/aktuellt/kalender/2025/digitala-kompetensdagen-2025/",
        "event-october-programming-name": "Kids' Programming Course",
        "event-october-programming-datetime": "October 27th–29th · 09.00–12.00",
        "event-october-programming-location": "Location: Växjö learning labs",
        "event-october-programming-language": "Languages: Swedish & English",
        "event-kids-programming-highlights-heading": "Highlights",
        "event-kids-programming-highlight-1": "Scratch programming course for children aged 10–12.",
        "event-kids-programming-highlight-2": "Delivered by TeMa Linné together with Kodcentrum.",
        "event-kids-programming-highlight-3": "Supported by Linnaeus University students plus new industry and community partners.",
        "event-kids-programming-highlight-4": "Offered in both Swedish and English to welcome all participants.",
        "event-kids-programming-overview-heading": "Overview",
        "event-kids-programming-overview-1": "During school holidays, TeMa Linné invites children aged 10–12 to an introductory Scratch course built on Kodcentrum’s learning material and led by skilled student instructors.",
        "event-kids-programming-overview-2": "Successful sessions in 2023–2024 sparked new collaborations with local companies and community organizations, allowing the course to keep growing.",
        "event-kids-programming-activities-heading": "Activities & sessions",
        "event-kids-programming-activity-1": "Hands-on Scratch programming sessions that build logic, creativity, and problem-solving skills.",
        "event-kids-programming-activity-2": "Guided instruction from student leaders from the Department of Computer Science and Media Technology.",
        "event-kids-programming-activity-3": "Inspirational visits and Q&As with developers from Sigma Technology AB and Softhouse.",
        "event-kids-programming-activity-4": "Mixed-language teaching (Swedish and English) so every participant feels included.",
        "event-kids-programming-activity-5": "Opportunities for children to explore campus and meet university student role models.",
        "event-kids-programming-instructors-heading": "Instructors & partners",
        "event-kids-programming-instructors-1": "Course leaders: Shota Napetvaridze, Maria Ihrmark, and Floris van Der Staaij.",
        "event-kids-programming-instructors-2": "Industry partners: Sigma Technology AB and Softhouse.",
        "event-kids-programming-instructors-3": "Community collaborators: Araby Park Arena and Centrumskolan in Växjö.",
        "event-kids-programming-instructors-4": "Content provider: Kodcentrum together with TeMa Linné’s student instructors.",
        "event-kids-programming-participation-heading": "Additional notes",
        "event-kids-programming-participation-1": "Collaborations with Araby Park Arena inspired deeper Scratch workshops and campus visits.",
        "event-kids-programming-participation-2": "Next course opportunity is planned for the upcoming school break (Påsklovet).",
        "event-kids-programming-participation-3": "Extra learning resources are available at Kodboken.se for children who want to keep coding at home.",
        "event-kids-programming-participation-4": "Read more: https://lnu.se/mot-linneuniversitetet/aktuellt/nyheter/2024/lyckat-samarbete-pa-programmeringskurs-for-barn/",
        "event-prao-45-name": "PRAO Week 45",
        "event-prao-45-datetime": "Week 45 · 3h per day (flexible)",
        "event-prao-45-location": "Location: Outreach venues in Växjö & Kalmar",
        "event-prao-45-language": "Languages: Swedish (support in English)",
        "event-karriardag-name": "Engineering Career Day",
        "event-karriardag-datetime": "November 18th · 08.00–15.30",
        "event-karriardag-location": "Location: Växjö campus",
        "event-karriardag-language": "Languages: Swedish (information in English available)",
        "event-karriardag-highlights-heading": "Highlights",
        "event-karriardag-highlight-1": "Full day of networking between companies, organisations, and students in construction, IT, and technology.",
        "event-karriardag-highlight-2": "Large career fair with exhibitors spread across multiple campus buildings.",
        "event-karriardag-highlight-3": "Speed-dating sessions for internships, thesis projects, and job opportunities.",
        "event-karriardag-highlight-4": "Open lectures from industry partners, startups, and university staff.",
        "event-karriardag-highlight-5": "Programme streams tailored for construction, technology, and IT students.",
        "event-karriardag-overview-heading": "Overview",
        "event-karriardag-overview-1": "Karriärdag Teknik/Byggardagen connects students with companies and organisations in technology, IT, and construction.",
        "event-karriardag-overview-2": "Students can build professional networks, explore internships, and find thesis collaborations or job paths.",
        "event-karriardag-overview-3": "Activities take place across Växjö campus with fairs, lectures, speed-dating, and competitions.",
        "event-karriardag-activities-heading": "Activities & sessions",
        "event-karriardag-activity-1": "Career fair featuring regional and national exhibitors located in Hus M, Hus K, Hus N, and nearby buildings.",
        "event-karriardag-activity-2": "Speed-dating sessions to book short meetings about internships, thesis proposals, and jobs.",
        "event-karriardag-activity-3": "Guest lectures from Volvo, Sigma Industry South, Skanska, Softwerk, and others.",
        "event-karriardag-activity-4": "Startup sessions led by LNU Innovation and Växjö Linnaeus Science Park on the journey from idea to company.",
        "event-karriardag-activity-5": "Student-focused talks about AI in studies, consulting vs employment, and career planning.",
        "event-karriardag-activity-6": "Meme competition with prizes in Glasgallerian and lunch wraps for registered participants.",
        "event-karriardag-locations-heading": "Key locations",
        "event-karriardag-location-1": "Växjö campus — Hus M, Hus K, Hus N, and surrounding buildings host fairs and lectures.",
        "event-karriardag-location-2": "Glasgallerian — prize ceremony for the Meme competition.",
        "event-karriardag-participation-heading": "Participation & resources",
        "event-karriardag-participation-1": "Open to students in construction, data/IT, engineering, and related programmes.",
        "event-karriardag-participation-2": "Resources include exhibitor lists (PDF), campus maps, speed-dating registration, exhibitor info, and travel guidance between Kalmar and Växjö.",
        "event-karriardag-participation-3": "Questions? Contact samverkan.ftk@lnu.se.",
        "event-karriardag-participation-4": "Official event page: https://lnu.se/mot-linneuniversitetet/aktuellt/kalender/2025/konferenser/karriardag-teknikbyggardagen-2025/",
        "event-student-life-talk-name": "Talk about Student Life at LNU",
        "event-student-life-talk-datetime": "November 18th · 1 hour",
        "event-student-life-talk-location": "Location: Local high schools (details provided upon request)",
        "event-student-life-talk-language": "Languages: Swedish (information in English available)",
        "event-prao-47-name": "PRAO Week 47",
        "event-prao-47-datetime": "Week 47 · 3h per day (flexible)",
        "event-prao-47-location": "Location: Outreach venues in Växjö & Kalmar",
        "event-prao-47-language": "Languages: Swedish (support in English)",
        "event-prao-highlights-heading": "Highlights",
        "event-prao-highlight-1": "Internship-style visit for pupils in grades 8–9 to explore programming and technology.",
        "event-prao-highlight-2": "Small-group teaching sessions with hands-on activities in Scratch and Python.",
        "event-prao-highlight-3": "Guided by students and staff from Linnaeus University.",
        "event-prao-highlight-4": "Focus on understanding basic programming concepts, problem-solving, and digital thinking.",
        "event-prao-highlight-5": "Offered twice per semester with a maximum of two pupils per week.",
        "event-prao-overview-heading": "Overview",
        "event-prao-overview-1": "PRAO Week (Praktisk arbetslivsorientering) gives pupils in grades 8–9 the chance to explore working life and gain insight into technology and programming at Linnaeus University.",
        "event-prao-overview-2": "During their visit, pupils take part in structured teaching sessions prepared by LNU students and staff, combining visual programming in Scratch with introductory Python coding.",
        "event-prao-overview-3": "The goal is to introduce fundamental concepts in computer science, build confidence in problem-solving, and show young learners what studying or working in the tech field can look like.",
        "event-prao-overview-4": "PRAO weeks are hosted twice per semester, with two pupils per week to ensure a personalized learning experience.",
        "event-prao-activities-heading": "Activities & sessions",
        "event-prao-activity-1": "Scratch programming basics that build sequences and event-driven thinking.",
        "event-prao-activity-2": "Asking for input and storing responses inside Scratch variables.",
        "event-prao-activity-3": "Logical comparisons with integer values that drive decisions.",
        "event-prao-activity-4": "Using if–else statements to explore multiple outcomes.",
        "event-prao-activity-5": "Changing sprites and costumes based on conditions to visualize logic.",
        "event-prao-activity-6": "Understanding how the structure of code leads to the on-screen behavior pupils see.",
        "event-prao-activity-7": "Guided transition from Scratch concepts to introductory Python.",
        "event-prao-activity-8": "Discussing the difference between strings and integers when working with data.",
        "event-prao-activity-9": "Taking user input and storing it in Python variables.",
        "event-prao-activity-10": "Printing and combining text with numeric values inside Python programs.",
        "event-prao-activity-11": "Writing simple conditional statements in Python using if/else.",
        "event-prao-activity-12": "Reading and interpreting basic error messages together with mentors.",
        "event-prao-activity-13": "Introduction to debugging techniques that help pupils fix mistakes.",
        "event-prao-activity-14": "Every session starts with a short concept presentation followed by hands-on practice.",
        "event-prao-schedule-heading": "Key locations",
        "event-prao-schedule-1": "Linnaeus University, Växjö campus — teaching labs and learning environments used for introductory programming workshops.",
        "event-prao-participation-heading": "Participation & resources",
        "event-prao-participation-1": "PRAO Week is intended for pupils in grades 8–9 as part of their practical workplace orientation period.",
        "event-prao-participation-2": "Participation is arranged together with schools, and each PRAO period hosts two pupils for tailored instruction.",
        "event-february-programming-name": "Kids' Programming Course",
        "event-february-programming-datetime": "February 16–18th · 09.00–12.00 or 13.00–16.00",
        "event-february-programming-location": "Location: Växjö learning labs",
        "event-february-programming-language": "Languages: Swedish (support in English)",
        "event-oppet-hus-vaxjo-name": "Open House · Växjö",
        "event-oppet-hus-vaxjo-datetime": "February 26th · 09.00–15.00",
        "event-oppet-hus-vaxjo-location": "Location: Växjö campus",
        "event-oppet-hus-vaxjo-language": "Languages: Swedish (support in English)",
        "event-oppet-hus-kalmar-name": "Open House · Kalmar",
        "event-oppet-hus-kalmar-datetime": "March 4th · 09.00–15.00",
        "event-oppet-hus-kalmar-location": "Location: Kalmar campus",
        "event-oppet-hus-kalmar-language": "Languages: Swedish (support in English)",
        "event-openhouse-kalmar-highlights-heading": "Highlights",
        "event-openhouse-kalmar-highlight-1": "Meet university staff, students, and study counsellors on Kalmar campus.",
        "event-openhouse-kalmar-highlight-2": "Explore programmes through inspirational sessions, general info talks, and hands-on activities.",
        "event-openhouse-kalmar-highlight-3": "Fair area open throughout the day with answers about student life, housing, and admissions.",
        "event-openhouse-kalmar-highlight-4": "Campus-wide tours and programme showcases running during the event.",
        "event-openhouse-kalmar-overview-heading": "Overview",
        "event-openhouse-kalmar-overview-1": "On 4 March 2026, Linnaeus University welcomes future students to Öppet hus on the Kalmar campus.",
        "event-openhouse-kalmar-overview-2": "Visitors can join talks, explore learning environments, meet current students, and get answers about programmes and applications.",
        "event-openhouse-kalmar-overview-3": "The fair is open 09.00–14.00 with inspirational sessions, general information talks, guided tours, and activities.",
        "event-openhouse-highlights-heading": "Highlights",
        "event-openhouse-highlight-1": "Recruit future students through inspirational sessions and fair activities.",
        "event-openhouse-highlight-2": "Offer guided tours, open labs, or sample lectures that showcase your programme.",
        "event-openhouse-highlight-3": "Plan for both morning and afternoon timeslots to meet visiting school groups.",
        "event-openhouse-overview-heading": "Overview",
        "event-openhouse-overview-1": "Open House is a perfect opportunity to recruit more students to your programme. During the events, you can increase visibility by running inspirational sessions and by taking part as an exhibitor at the fair. You can also register a guided tour or another activity of your choice—such as a visit to your programme’s facilities, an open lab, or a sample lecture.",
        "event-openhouse-overview-2": "Open House is one of Linnaeus University’s largest recruitment initiatives of the academic year, and in 2025 nearly 2 500 people visited across both the Växjö and Kalmar campuses. Most visitors come from upper secondary schools in Småland and Blekinge, but we also welcome many from further afield across Sweden.",
        "event-openhouse-overview-3": "Since 2025, Open House has been a joint event for both campuses, with the project group aiming to present a similar range of activities for visitors regardless of whether they choose to attend in Växjö or in Kalmar.",
        "event-openhouse-expectations-heading": "Different ways to take part",
        "event-openhouse-expectation-1": "The inspirational sessions give you the opportunity to explain why students should choose your programme. They may be led by the programme coordinator, a study counsellor, or current students. We recommend involving students in some way so they can describe everyday life as a student. Each session lasts 20 minutes, during which you present your programme and host a Q&A.",
        "event-openhouse-expectation-2": "The fair is an opportunity to have in-depth conversations with prospective students. It's also a great way to make your programme visible and generate interest among visitors who may not attend your specific inspiration session. We recommend planning an activity at your stand to make it easier to attract visitors.",
        "event-openhouse-expectation-3": "Guided tours and activities offer a chance to showcase a specific learning environment or highlight an aspect of your programme. This could include opening up a lab, a tour of a studio, a concert with students, or a hands-on activity. Feel free to come up with your own ideas!",
        "event-openhouse-schedule-heading": "Open House 2026 schedule",
        "event-openhouse-schedule-1": "Campus Växjö — Thursday 26 February at 9 am–2 pm",
        "event-openhouse-schedule-2": "Campus Kalmar — Wednesday 4 March at 9 am–2 pm",
        "event-openhouse-schedule-3": "Each inspirational session should be offered at least once in the morning and once in the afternoon to accommodate visiting schools.",
        "event-openhouse-participation-heading": "Participation & registration",
        "event-openhouse-participation-1": "Registration for participation at Open House 2026 is open from 1 September and closes on 31 October.",
        "event-openhouse-participation-2": "Register here.",
        "event-openhouse-participation-3": "Any questions? Contact the project group for Open House at oppethus@lnu.se.",
        "event-openhouse-participation-4": "See information published for external visitors.",
        "event-igeday-name": "IGEDAY",
        "event-igeday-datetime": "March 20th · 09.00–15.00",
        "event-igeday-location": "Location: Växjö campus",
        "event-igeday-language": "Languages: Swedish (information in English available · women only)",
        "event-igeday-highlights-heading": "Highlights",
        "event-igeday-highlight-1": "National initiative introducing girls and non-binary youth to life as an engineer.",
        "event-igeday-highlight-2": "Participants aged 13–19 get hands-on experiences at real engineering workplaces across Sweden.",
        "event-igeday-highlight-3": "Company participation is open to organizations with at least one woman engineer.",
        "event-igeday-highlight-4": "Supported and organized by the Womengineer Foundation.",
        "event-igeday-highlight-5": "Focus on empowering young people to explore engineering and choose their future with confidence.",
        "event-igeday-overview-heading": "Overview",
        "event-igeday-overview-1": "IGEday is a nationwide event where girls and non-binary individuals aged 13–19 explore what it's like to work as an engineer while companies across Sweden host interactive sessions, workshops, and hands-on activities.",
        "event-igeday-overview-2": "The next IGEday takes place on March 20, 2026, with participant registration opening on January 7.",
        "event-igeday-overview-3": "The initiative inspires young people to view engineering as an exciting, accessible career path, with recurring hosts such as Siemens Energy, E.ON, and Tetra Pak.",
        "event-igeday-activities-heading": "Activities & sessions",
        "event-igeday-activity-1": "Guided tours of engineering workplaces that showcase labs, control rooms, and project spaces.",
        "event-igeday-activity-2": "Hands-on problem-solving sessions where participants build prototypes, test ideas, and collaborate with engineers.",
        "event-igeday-activity-3": "Talks from engineers and role models sharing study paths, daily work, and tips for choosing programmes.",
        "event-igeday-activity-4": "Group challenges, teamwork activities, and Q&A opportunities about studies and career paths.",
        "event-igeday-activity-5": "Teachers, mentors, and student counsellors are welcome to accompany groups and support the experience.",
        "event-igeday-activity-6": "Inspirational stories from women engineers and young participants highlighting different futures within technology.",
        "event-igeday-schedule-heading": "Key dates & host updates",
        "event-igeday-schedule-1": "Company participation is open to any organization with at least one woman engineer, and registration for IGEday 2026 hosts closes on November 30.",
        "event-igeday-schedule-2": "Participant registration opens on January 7, with the list of participating companies updated continuously at https://igeday.com so applicants can choose their preferred workplace.",
        "event-igeday-schedule-3": "On March 20, 2026, hosts across Sweden run morning or full-day sessions, from factory tours to innovation workshops.",
        "event-igeday-participation-heading": "Participation & resources",
        "event-igeday-participation-1": "Anyone aged 13–19 who identifies as a girl or non-binary can sign up individually or as part of a school group.",
        "event-igeday-participation-2": "Hosts need at least one woman engineer and can design tours, workshops, or lab sessions that reflect their workplace and teams.",
        "event-igeday-participation-3": "Quotes from previous participants include \"The best part was hearing what life as an engineer is like.\", \"The most fun part was solving tasks together.\", and \"I got to see what my future workplace might look like!\"",
        "event-igeday-participation-4": "IGEday is organized by the Womengineer Foundation, whose goal is for Sweden to graduate as many female engineers as male engineers by 2030 while supporting UN Sustainable Development Goals 4, 5, and 10.",
        "event-igeday-participation-5": "The initiative is made possible through partners, schools, companies, and volunteers across Sweden who coordinate logistics and mentoring.",
        "event-igeday-participation-6": "More information, FAQs, and inspiration from previous years are available on the official website: https://igeday.com.",
        "event-march-programming-name": "Kids' Programming Course",
        "event-march-programming-datetime": "March 30th–April 1st · 09.00–12.00 or 13.00–16.00",
        "event-march-programming-location": "Location: Växjö learning labs",
        "event-march-programming-language": "Languages: Swedish (support in English)",
        "event-science-linne-name": "Science Linné",
        "event-science-linne-datetime": "April 24–25th",
        "event-science-linne-location": "Location: Växjö campus",
        "event-science-linne-language": "Languages: Swedish (information in English available)",
        "event-science-linne-highlights-heading": "Highlights",
        "event-science-linne-highlight-1": "Annual science and technology festival attracting over 1,000 visitors.",
        "event-science-linne-highlight-2": "Hands-on experiments, demonstrations, and challenges for students and the public.",
        "event-science-linne-highlight-3": "Exhibitors from Linnaeus University and regional tech companies.",
        "event-science-linne-highlight-4": "Activities spanning LEGO engineering, robotics, biology, VR, and structural engineering.",
        "event-science-linne-highlight-5": "Designed to spark interest in technology, science, and mathematics.",
        "event-science-linne-overview-heading": "Overview",
        "event-science-linne-overview-1": "Science City transforms Växjö campus into a vibrant environment filled with tech, science, and excitement.",
        "event-science-linne-overview-2": "More than 1,000 visitors explored interactive stations, live demos, and creative challenges.",
        "event-science-linne-overview-3": "Exhibitors from LNU and regional companies showcased everything from robotics to environmental science.",
        "event-science-linne-activities-heading": "Activities & sessions",
        "event-science-linne-activity-1": "Full-scale LEGO Volvo V70 exhibited by LEGO Masters Sverige winner David Gustafsson.",
        "event-science-linne-activity-2": "Engineering challenges: catapult building, 3D virtual airplanes, and remote-controlled car testing.",
        "event-science-linne-activity-3": "Creative making: turning wooden apples, structure building, and math magic tricks.",
        "event-science-linne-activity-4": "Science exploration: observing algae via microscopes and tasting algae smoothies.",
        "event-science-linne-activity-5": "Technology showcases: industrial robots, student-built dance mats, and VR experiences.",
        "event-science-linne-activity-6": "“Starkast vinner!” bridge-building competition with bridges carrying over 40 kg.",
        "event-science-linne-activity-7": "Morning entry for grades 5–9 (pre-booked) and afternoon access for upper-secondary students and the public.",
        "event-science-linne-partners-heading": "Partners & collaborators",
        "event-science-linne-partners-1": "Organized by Linnaeus University with Epic; sponsored by Teknikcollege and Växjö municipality.",
        "event-science-linne-partners-2": "Supported by university staff, student volunteers, and regional tech companies.",
        "event-science-linne-partners-3": "Project leaders Laure Fournier and Katrin Lindwall emphasize inspiring young people with tech education.",
        "event-science-linne-locations-heading": "Key locations",
        "event-science-linne-location-1": "Växjö campus — multiple buildings and open areas host booths, workshops, and demos.",
        "event-science-linne-participation-heading": "Participation & resources",
        "event-science-linne-participation-1": "More info and photos: https://lnu.se/mot-linneuniversitetet/aktuellt/nyheter/2023/dricka-alger-bygga-broar-och-svarva-applen--science-city-gav-manga-smakprov-for-den-teknikintresserade/",
        "event-june-programming-name": "Kids' Programming Course",
        "event-june-programming-datetime": "June 15–17th · 09.00–12.00 or 13.00–16.00",
        "event-june-programming-location": "Location: Växjö learning labs",
        "event-june-programming-language": "Languages: Swedish (support in English)",
        "faq-title": "Frequently Asked Questions",
        "faq1-question": "Who can join the Tutorial Education Program?",
        "faq1-answer": "Undergraduate students from their second year onward and master's students enrolled in Computer Science or Media Technology at LNU.",
        "faq2-question": "Do I need previous teaching experience?",
        "faq2-answer": "No. We provide mentoring, onboarding workshops, and resources to help you feel confident supporting your peers.",
        "faq3-question": "How much time do I have to commit?",
        "faq3-answer": "You can work part-time at 25% or 50% depending on course load and availability. We schedule activities to fit your studies.",
        "faq4-question": "What types of projects will I work on?",
        "faq4-answer": "Assignments range from lab tutoring and research support to community workshops, coding clubs, and outreach events.",
    },
    sv: {
        "about-title": "Om Oss",
        "about-description": "Vi är en grupp studenter som deltar i olika projekt på universitetet. Vi hjälper andra studenter som handledare i labbsessioner, bidrar till den pågående forskningen på universitetet och stödjer samhällsarbetet som görs för att intressera fler för datavetenskap och programmering.",
        "about-hero-eyebrow": "Bakom Tutorial Education Program",
        "about-hero-list-1": "Labsupport och mentorskap",
        "about-hero-list-2": "Outreach och event på hela universitetet",
        "about-hero-list-3": "Outreach och event i hela Sverige",
        "header-projects": "Projekt",
        "header-events": "Evenemang",
        "header-aboutUs": "Om Oss",
        "header-english": "Engelska",
        "header-swedish": "Svenska",
        "hero-eyebrow": "Tutorial Education Program",
        "hero-heading": "Gör skillnad under dina studier.",
        "hero-cta-primary": "Möt teamet",
        "hero-cta-secondary": "Utforska aktuella projekt",
        "hero-highlight-eyebrow": "Just nu hos TEP",
        "hero-stat-projects-label": "Pågående projekt",
        "hero-stat-projects-sub": "Uppdateras varje vecka",
        "hero-stat-events-label": "Kommande event",
        "hero-stat-events-sub": "I Växjö och Kalmar",
        "hero-next-event-eyebrow": "Nästa i kalendern",
        "TEP-description": "Utforska flexibla roller som kombinerar handledning, forskning och outreach medan du studerar vid Linnéuniversitetet.",
        "projects-hero-eyebrow": "Projekt & Initiativ",
        "projects-hero-heading": "Studentdrivna lösningar över LNU.",
        "projects-hero-lead": "Upptäck hur team inom Tutorial Education Program stöttar labbar, forskningspiloter och outreach varje termin.",
        "projects-hero-cta-primary": "Bläddra bland aktuella projekt",
        "projects-hero-cta-secondary": "Föreslå en ny idé",
        "projects-hero-stat-active-label": "Aktiva projekt",
        "projects-hero-stat-active-sub": "Samarbeten den här terminen",
        "projects-hero-stat-members-label": "Engagerade studenter",
        "projects-hero-stat-members-sub": "På campus i Växjö & Kalmar",
        "projects-hero-latest-label": "Senaste starten",
        "projects-hero-pill-label": "Fokusområden",
        "projects-library-eyebrow": "Projektbibliotek",
        "projects-library-title": "Utforska alla initiativ",
        "projects-library-description": "Sorterade från senaste. Öppna ett kort för detaljer, team och resultat.",
        "events-title": "Evenemang & Outreach",
        "events-lead": "Utforska outreach, öppet hus och programmeringsaktiviteter där TEP-studenter gör skillnad.",
        "events-instructions": "Klicka på en ruta för att öppna evenemangssidan.",
        "event-status-completed": "Genomförd",
        "team-title": "Vår Team",
        "team-description": "Vårt team består av studenter från hela världen som studerar olika program vid LNU.",
        "team-alumni-title": "Alumner",
        "team-alumni-description": "Tidigare TEP-medlemmar som fortsätter göra skillnad.",
        "team-alumni-badge": "Alumn",
        "team-empty-current": "Inga aktiva medlemmar att visa just nu.",
        "team-empty-alumni": "Alumner presenteras snart.",
        "member1-name": "Medlem 1",
        "member1-info": "Programnamn, studieår",
        "member1-quote": "Här skriver jag på svenska!",
        "member1-projects": [
        { name: "Projekt A", link: "#" },
        { name: "Projekt B", link: "#" }
        ],
        "member2-name": "Medlem 2",
        "member2-info": "Programnamn, studieår",
        "member2-quote": "Här skriver jag på svenska!",
        "member2-projects": [
        { name: "Projekt A", link: "#" },
        { name: "Projekt B", link: "#" }
        ],
        "member3-name": "Medlem 3",
        "member3-info": "Programnamn, studieår",
        "member3-quote": "Här skriver jag på svenska!",
        "member3-projects": [
        { name: "Projekt A", link: "#" },
        { name: "Projekt B", link: "#" }
        ],
        "member4-name": "Medlem 4",
        "member4-info": "Programnamn, studieår",
        "member4-quote": "Här skriver jag på svenska!",
        "member4-projects": [
        { name: "Projekt A", link: "#" },
        { name: "Projekt B", link: "#" }
        ],
        "member5-name": "Medlem 5",
        "member5-info": "Programnamn, studieår",
        "member5-quote": "Här skriver jag på svenska!",
        "member5-projects": [
        { name: "Projekt A", link: "#" },
        { name: "Projekt B", link: "#" }
        ],
        "member6-name": "Medlem 6",
        "member6-info": "Programnamn, studieår",
        "member6-quote": "Här skriver jag på svenska!",
        "member6-projects": [
        { name: "Projekt A", link: "#" },
        { name: "Projekt B", link: "#" }
        ],
        "member7-name": "Medlem 7",
        "member7-info": "Programnamn, studieår",
        "member7-quote": "Här skriver jag på svenska!",
        "member7-projects": [
        { name: "Projekt A", link: "#" },
        { name: "Projekt B", link: "#" }
        ],
        "member8-name": "Medlem 8",
        "member8-info": "Programnamn, studieår",
        "member8-quote": "Här skriver jag på svenska!",
        "member8-projects": [
        { name: "Projekt A", link: "#" },
        { name: "Projekt B", link: "#" }
        ],
        "mission-title": "Vårt uppdrag",
        "mission-description": "TEP ger studenter möjlighet att växa som lärare, forskare och samhällsbyggare samtidigt som de bidrar till meningsfulla projekt vid Linnéuniversitetet.",
        "mission-point-1": "Utveckla handledningssäkerhet genom stöd i labbsessioner.",
        "mission-point-2": "Utforska tillämpad forskning tillsammans med lärare.",
        "mission-point-3": "Driv aktiviteter som inspirerar framtida studenter.",
        "mission-events-cta": "Se kommande evenemang",
        "what-is-tep-title": "Vad är TEP?",
        "what-is-tep-description": "Tutorial Education Program erbjuder flexibla, avlönade uppdrag för studenter som vill stärka sitt CV, utveckla akademiska färdigheter och påverka campus.",
        "what-is-tep-highlight-1": "Strukturerad handledning och utbildning av erfarna medarbetare.",
        "what-is-tep-highlight-2": "Möjligheter att koppla kursarbete till verkliga projekt.",
        "what-is-tep-highlight-3": "Stöd för både engelsktalande och svensktalande studenter.",
        "pillars-title": "Våra tre pelare",
        "pillars-description": "Varje deltagare kombinerar ansvar inom undervisning, forskning och samhällsarbete. Du kan fokusera på ett spår eller växla beroende på intresse och tillgänglighet.",
        "pillar-ta-title": "Labb- och undervisningsstöd",
        "pillar-ta-description": "Stötta labbsessioner, svara på kursfrågor och hjälp klasskamrater att förstå svåra koncept.",
        "pillar-ta-point-1": "Flexibla handledningstimmar som passar runt dina studier.",
        "pillar-ta-point-2": "Praktisk klassrumserfarenhet med återkoppling från lärare.",
        "pillar-research-title": "Forskningsstöd",
        "pillar-research-description": "Arbeta tillsammans med lärare i pågående projekt – från dataanalys till prototyper och dokumentation.",
        "pillar-research-point-1": "Praktisk träning i akademiska metoder och verktyg.",
        "pillar-research-point-2": "Skapa resultat som du stolt kan visa i ditt CV.",
        "pillar-community-title": "Samhällsengagemang",
        "pillar-community-description": "Planera evenemang och workshops som bjuder in nya röster till IT och lyfter mångfald.",
        "pillar-community-point-1": "Samarbeta med skolor, föreningar och lokala partners.",
        "pillar-community-point-2": "Inspirera framtida studenter genom interaktiva aktiviteter.",
        "community-title": "Redo att söka?",
        "community-description": "Gå med i Tutorial Education Program och hjälp oss leverera labb, forskningsstöd och outreach på Linnéuniversitetet.",
        "community-cta-primary": "Ansök nu",
        "community-cta-secondary": "Se våra medlemmar",
        "community-requirement-title": "Förkunskaper",
        "community-requirement-1": "Inskriven student vid Linnéuniversitetet.",
        "community-requirement-2": "År 2 på kandidat eller master inom datavetenskap eller medieteknik.",
        "community-requirement-3": "Nyfiken på undervisning, forskning eller outreach.",
        "community-workload-title": "Välj omfattning",
        "community-workload-1": "25 % deltid (ca 10 h/vecka).",
        "community-workload-2": "50 % deltid (ca 20 h/vecka).",
        "community-workload-3": "Schema anpassat efter dina kurser.",
        "community-support-title": "Detta får du",
        "community-support-1": "Mentorskap från erfarna handledare.",
        "community-support-2": "Praktisk erfarenhet till ditt CV.",
        "community-support-3": "Tillgång till evenemang, workshops och projektteam.",
        "event-tag-outreach": "Samhällsengagemang",
        "event-tag-course": "Kurs",
        "event-tag-career": "Karriär",
        "event-tag-openhouse": "Öppet hus",
        "event-digitalidag-name": "Digitalidag",
        "event-digitalidag-datetime": "10 oktober · 13.00–17.00",
        "event-digitalidag-location": "Plats: Linnéuniversitetet (detaljer kommer snart)",
        "event-digitalidag-language": "Språk: Svenska (information på engelska finns)",
        "event-digitalidag-highlights-heading": "Höjdpunkter",
        "event-digitalidag-highlight-1": "Nationellt Digitalidag-program med unika sessioner från Linnéuniversitetet.",
        "event-digitalidag-highlight-2": "Aktiviteter på båda campus och i lokala arenor i Kalmar och Växjö.",
        "event-digitalidag-highlight-3": "Fokus på cybersäkerhet, AI, digital transformation och lekfullt lärande för alla åldrar.",
        "event-digitalidag-overview-heading": "Översikt",
        "event-digitalidag-overview-1": "Digitalidag är en nationell temadag fylld med digitala aktiviteter, workshops och samtal i hela Sverige.",
        "event-digitalidag-overview-2": "Linnéuniversitetet bidrar med expertföreläsningar, interaktiva labb och publika aktiviteter för studenter, familjer, yrkesverksamma och det lokala samhället.",
        "event-digitalidag-overview-3": "Programmet spänner över cybersäkerhet, AI, digital transformation och lekfullt lärande på Universitetskajen i Kalmar, campus Växjö, Araby Park Arena och Växjö stadsbibliotek.",
        "event-digitalidag-activities-heading": "Aktiviteter & sessioner",
        "event-digitalidag-activity-1": "Panelsamtal om cybersäkerhet (Kalmar · Hus Stella) där kommunledare, branschexperter och LNU:s IT-specialister diskuterar hackerhot. Medverkande: Christoffer Carlsson Schött, Niklas Hörling, Louise Östlund, Henrik Ryttergard, Peter Bergehamn och Pär Igevik.",
        "event-digitalidag-activity-2": "Frukostmöte ”Konkurrenskraft genom digitalisering” (Kalmar Business Lab) tillsammans med Smålandsnavet där John Jeansson och Krister Bredmar visar hur digitalisering stärker konkurrenskraft.",
        "event-digitalidag-activity-3": "Experimentverkstad om Generativ AI (campus Växjö) med Jonas Svensson om AI-verktyg, människa–maskin-interaktion och projektet Människa, maskin, samhälle.",
        "event-digitalidag-activity-4": "Lek och lär-labb (Araby Park Arena) där barn utforskar digital kreativitet genom lekfulla stationer.",
        "event-digitalidag-activity-5": "Öppen föreläsning om IoT & AI (Växjö stadsbibliotek) där Jonas Nordqvist visar möjligheter och utmaningar med datadriven innovation.",
        "event-digitalidag-schedule-heading": "Viktiga platser",
        "event-digitalidag-schedule-1": "Universitetskajen, Kalmar – panel om cybersäkerhet, frukostmöte och outreach-aktiviteter.",
        "event-digitalidag-schedule-2": "Campus Växjö – experimentverkstäder om Generativ AI och studentledda demonstrationer.",
        "event-digitalidag-schedule-3": "Lokala arenor – Lek och lär i Araby Park Arena samt offentlig föreläsning på Växjö stadsbibliotek dagen före Digitalidag.",
        "event-digitalidag-participation-heading": "Deltagande & resurser",
        "event-digitalidag-participation-1": "Digitalidag är Sveriges nationella satsning för att stärka digital delaktighet och kunskap.",
        "event-digitalidag-participation-2": "Linnéuniversitetet bidrar varje år med ett brett program över båda campus och i närsamhället.",
        "event-digitalidag-participation-3": "Mer information: Digitalidag på Linnéuniversitetet · Digitalidag Sverige.",
        "event-digitalidag-participation-4": "Senaste nyheten: https://lnu.se/mot-linneuniversitetet/aktuellt/nyheter/2024/digitalidag-2024/",
        "event-vera-dagen-name": "VERA-dagen på Volvo",
        "event-vera-dagen-datetime": "16 oktober",
        "event-vera-dagen-location": "Plats: Volvo CE, Braås",
        "event-vera-dagen-language": "Språk: Svenska (stöd på engelska)",
        "event-vera-dagen-highlights-heading": "Höjdpunkter",
        "event-vera-dagen-highlight-1": "Inspirationsdag i teknik för elever i årskurs 5 med fokus på kreativitet och ingenjörstänk.",
        "event-vera-dagen-highlight-2": "Arrangeras av Volvo CE i Braås tillsammans med deltagande studenter från Linnéuniversitetet.",
        "event-vera-dagen-highlight-3": "Praktiska pass om säkerhet, innovation, VR-upplevelser och introducerande kodning.",
        "event-vera-dagen-highlight-4": "Uppmuntrar unga tjejer att vara nyfikna på teknik och se framtida ingenjörskarriärer.",
        "event-vera-dagen-overview-heading": "Översikt",
        "event-vera-dagen-overview-1": "VERA-dagen på Volvo är ett initiativ som ska inspirera unga tjejer att utforska teknik, innovation och ingenjörskap.",
        "event-vera-dagen-overview-2": "Volvo CE i Braås välkomnar två klasser i årskurs 5 för att lära sig hur ingenjörer tänker, skapar och löser verkliga problem.",
        "event-vera-dagen-overview-3": "Två studenter från Linnéuniversitetet ansluter på plats och hjälper Volvosteamet att leda aktiviteterna och svara på frågor.",
        "event-vera-dagen-overview-4": "Syftet är att väcka tidigt intresse för STEM och visa att teknik är kreativ, meningsfull och tillgänglig för alla.",
        "event-vera-dagen-activities-heading": "Aktiviteter & pass",
        "event-vera-dagen-activity-1": "Innovationsutmaningar där elever brainstormar hur teknik kan göra trafiken säkrare.",
        "event-vera-dagen-activity-2": "Gruppvis problemlösning där idéer presenteras och olika angreppssätt diskuteras.",
        "event-vera-dagen-activity-3": "VR-demonstrationer som låter eleverna uppleva ingenjörskoncept virtuellt.",
        "event-vera-dagen-activity-4": "Introduktion till programmering med övningar som visar logik, kreativitet och digitalt skapande.",
        "event-vera-dagen-activity-5": "Teknikstationer som visar hur Volvo CE:s ingenjörer utvecklar maskiner, säkerhetslösningar och framtidens mobilitet.",
        "event-vera-dagen-activity-6": "Gemensam avslutning där eleverna delar sina kreativa lösningar.",
        "event-vera-dagen-schedule-heading": "Viktiga platser",
        "event-vera-dagen-schedule-1": "Volvo CE, Braås – ingenjörsmiljöer och aktivitetsrum för workshops, VR och innovationspass.",
        "event-vera-dagen-participation-heading": "Deltagande & resurser",
        "event-vera-dagen-participation-1": "VERA-dagen arrangeras av Volvo CE för att tidigt väcka intresse för ingenjörsyrken, med särskilt fokus på att uppmuntra tjejer att välja STEM.",
        "event-vera-dagen-participation-2": "Två studenter från LNU stöttar på plats, leder workshops och guidar diskussioner. För mer information eller bilder, kontakta arrangörsteamet.",
        "event-digitala-kompetensdagen-name": "Digitala kompetensdagen",
        "event-digitala-kompetensdagen-datetime": "28 oktober · 08.00–16.00",
        "event-digitala-kompetensdagen-location": "Plats: Campus Växjö · Hus K",
        "event-digitala-kompetensdagen-language": "Språk: Endast svenska",
        "event-digitala-kompetensdagen-highlights-heading": "Höjdpunkter",
        "event-digitala-kompetensdagen-highlight-1": "Årlig konferens för pedagoger och skolledare i Kronobergs län.",
        "event-digitala-kompetensdagen-highlight-2": "Fokus på digital kompetens, nya verktyg, pedagogisk innovation och digital transformation.",
        "event-digitala-kompetensdagen-highlight-3": "Arrangeras tillsammans av AV-Media Region Kronoberg och Linnéuniversitetet på campus Växjö.",
        "event-digitala-kompetensdagen-overview-heading": "Översikt",
        "event-digitala-kompetensdagen-overview-1": "Digitala kompetensdagen är en heldagskonferens som stärker den digitala kompetensen hos regionens pedagoger och skolledare.",
        "event-digitala-kompetensdagen-overview-2": "Deltagarna får nya idéer, verktyg och kunskap samt omvärldsbevakning inom digitalt lärande.",
        "event-digitala-kompetensdagen-overview-3": "År 2025 hålls konferensen den 28 oktober på Linnéuniversitetet i Växjö, i samarbete med AV-Media Region Kronoberg.",
        "event-digitala-kompetensdagen-activities-heading": "Aktiviteter & sessioner",
        "event-digitala-kompetensdagen-activity-1": "Presentationer och workshops om digitala pedagogiska verktyg och digital transformation i skolan.",
        "event-digitala-kompetensdagen-activity-2": "Pass om klassrumsinnovation med nya arbetssätt och goda exempel för digitalt lärande.",
        "event-digitala-kompetensdagen-activity-3": "Ledsagade diskussioner om möjligheter, utmaningar och framtidskompetenser.",
        "event-digitala-kompetensdagen-schedule-heading": "Viktiga platser",
        "event-digitala-kompetensdagen-schedule-1": "Campus Växjö · Hus K står värd för plenumpass och huvudsakliga sessioner.",
        "event-digitala-kompetensdagen-schedule-2": "Närliggande lärmiljöer på campus används för workshops och mindre grupper.",
        "event-digitala-kompetensdagen-participation-heading": "Deltagande & partners",
        "event-digitala-kompetensdagen-participation-1": "Digitala kompetensdagen arrangeras gemensamt av AV-Media Region Kronoberg och Linnéuniversitetet.",
        "event-digitala-kompetensdagen-participation-2": "Programuppdateringar och anmälan publiceras på evenemangets webbsida.",
        "event-digitala-kompetensdagen-participation-3": "Besöksinformation, inklusive rese- och campusinfo, finns online.",
        "event-digitala-kompetensdagen-participation-4": "Läs mer: https://lnu.se/mot-linneuniversitetet/aktuellt/kalender/2025/digitala-kompetensdagen-2025/",
        "event-october-programming-name": "Programmeringskurs för barn",
        "event-october-programming-datetime": "27–29 oktober · 09.00–12.00",
        "event-october-programming-location": "Plats: Lärlabb i Växjö",
        "event-october-programming-language": "Språk: Svenska och engelska",
        "event-kids-programming-highlights-heading": "Höjdpunkter",
        "event-kids-programming-highlight-1": "Scratchkurs i programmering för barn 10–12 år.",
        "event-kids-programming-highlight-2": "Genomförs av TeMa Linné tillsammans med Kodcentrum.",
        "event-kids-programming-highlight-3": "Stöds av studenter från Linnéuniversitetet samt nya partners från näringsliv och samhälle.",
        "event-kids-programming-highlight-4": "Ges på både svenska och engelska för att inkludera alla.",
        "event-kids-programming-overview-heading": "Översikt",
        "event-kids-programming-overview-1": "Under skolloven bjuder TeMa Linné in barn 10–12 år till en introduktionskurs i Scratch baserad på Kodcentrums material och ledd av engagerade studentinstruktörer.",
        "event-kids-programming-overview-2": "Lyckade omgångar under 2023–2024 har lett till nya samarbeten med lokala företag och samhällsorganisationer, vilket låter kursen växa.",
        "event-kids-programming-activities-heading": "Aktiviteter & sessioner",
        "event-kids-programming-activity-1": "Praktiska Scratch-pass som tränar logik, kreativitet och problemlösning.",
        "event-kids-programming-activity-2": "Handledda lektioner av studenter från Institutionen för datavetenskap och medieteknik.",
        "event-kids-programming-activity-3": "Inspirationsbesök och frågestunder med utvecklare från Sigma Technology AB och Softhouse.",
        "event-kids-programming-activity-4": "Undervisning på både svenska och engelska så att alla deltagare känner sig inkluderade.",
        "event-kids-programming-activity-5": "Möjlighet för barnen att upptäcka campus och träffa studentförebilder.",
        "event-kids-programming-instructors-heading": "Instruktörer & partners",
        "event-kids-programming-instructors-1": "Kursledare: Shota Napetvaridze, Maria Ihrmark och Floris van Der Staaij.",
        "event-kids-programming-instructors-2": "Industripartners: Sigma Technology AB och Softhouse.",
        "event-kids-programming-instructors-3": "Samhällspartners: Araby Park Arena och Centrumskolan i Växjö.",
        "event-kids-programming-instructors-4": "Innehållsleverantör: Kodcentrum tillsammans med TeMa Linnés studentinstruktörer.",
        "event-kids-programming-participation-heading": "Övrig information",
        "event-kids-programming-participation-1": "Samarbetet med Araby Park Arena inspirerade fördjupade Scratch-workshops och campusbesök.",
        "event-kids-programming-participation-2": "Nästa kursomgång planeras till kommande skollov (Påsklovet).",
        "event-kids-programming-participation-3": "Extra lärresurser finns på Kodboken.se för barn som vill fortsätta programmera hemma.",
        "event-kids-programming-participation-4": "Läs mer: https://lnu.se/mot-linneuniversitetet/aktuellt/nyheter/2024/lyckat-samarbete-pa-programmeringskurs-for-barn/",
        "event-prao-45-name": "PRAO vecka 45",
        "event-prao-45-datetime": "Vecka 45 · 3 h per dag (flexibelt)",
        "event-prao-45-location": "Plats: Utåtriktade arenor i Växjö & Kalmar",
        "event-prao-45-language": "Språk: Svenska (stöd på engelska)",
        "event-karriardag-name": "Karriärdag teknik",
        "event-karriardag-datetime": "18 november · 08.00–15.30",
        "event-karriardag-location": "Plats: Campus Växjö",
        "event-karriardag-language": "Språk: Svenska (information på engelska finns)",
        "event-karriardag-highlights-heading": "Höjdpunkter",
        "event-karriardag-highlight-1": "Heldag med nätverkande mellan företag, organisationer och studenter inom bygg, IT och teknik.",
        "event-karriardag-highlight-2": "Stor karriärmässa med utställare i flera campusbyggnader.",
        "event-karriardag-highlight-3": "Speed-dating-pass för praktik, examensarbeten och jobb.",
        "event-karriardag-highlight-4": "Öppna föreläsningar med branschpartners, startups och universitetslärare.",
        "event-karriardag-highlight-5": "Särskilda programspår för bygg-, teknik- och IT-studenter.",
        "event-karriardag-overview-heading": "Översikt",
        "event-karriardag-overview-1": "Karriärdag Teknik/Byggardagen kopplar samman studenter med företag inom teknik, IT och byggsektorn.",
        "event-karriardag-overview-2": "Målet är att ge studenter chans att bygga nätverk, hitta praktikplatser, examensjobb och framtida karriärvägar.",
        "event-karriardag-overview-3": "Besökare kan träffa arbetsgivare, gå på föreläsningar, delta i speed-dating och aktiviteter över hela campus.",
        "event-karriardag-activities-heading": "Aktiviteter & pass",
        "event-karriardag-activity-1": "Karriärmässa med regionala och nationella utställare i Hus M, Hus K, Hus N och intilliggande byggnader.",
        "event-karriardag-activity-2": "Speed-dating där studenter bokar korta möten om praktik, examensarbeten och jobb.",
        "event-karriardag-activity-3": "Gästföreläsningar från Volvo, Sigma Industry South, Skanska, Softwerk m.fl.",
        "event-karriardag-activity-4": "Startuppass med LNU Innovation och Växjö Linnaeus Science Park om resan från idé till företag.",
        "event-karriardag-activity-5": "Studentinriktade föredrag om AI och arbetsmarknaden, konsult vs anställning och karriärtips.",
        "event-karriardag-activity-6": "Meme-tävling med prisutdelning i Glasgallerian samt lunchwraps för anmälda deltagare.",
        "event-karriardag-locations-heading": "Viktiga platser",
        "event-karriardag-location-1": "Campus Växjö – Hus M, Hus K, Hus N och närliggande byggnader rymmer mässor och föreläsningar.",
        "event-karriardag-location-2": "Glasgallerian – prisutdelning för Meme-tävlingen.",
        "event-karriardag-participation-heading": "Deltagande & resurser",
        "event-karriardag-participation-1": "Öppet för studenter inom bygg, data/IT, ingenjörs- och teknikutbildningar.",
        "event-karriardag-participation-2": "Resurser: utställarlistor (PDF), kartor för K- och M-huset, speed-datinganmälan, info för utställare och reseinformation Kalmar ↔ Växjö.",
        "event-karriardag-participation-3": "Frågor: samverkan.ftk@lnu.se.",
        "event-karriardag-participation-4": "Officiell sida: https://lnu.se/mot-linneuniversitetet/aktuellt/kalender/2025/konferenser/karriardag-teknikbyggardagen-2025/",
        "event-student-life-talk-name": "Föreläsning om studentliv på LNU",
        "event-student-life-talk-datetime": "18 november · 1 timme",
        "event-student-life-talk-location": "Plats: Gymnasieskolor (detaljer ges vid förfrågan)",
        "event-student-life-talk-language": "Språk: Svenska (information på engelska finns)",
        "event-prao-47-name": "PRAO vecka 47",
        "event-prao-47-datetime": "Vecka 47 · 3 h per dag (flexibelt)",
        "event-prao-47-location": "Plats: Utåtriktade arenor i Växjö & Kalmar",
        "event-prao-47-language": "Språk: Svenska (stöd på engelska)",
        "event-prao-highlights-heading": "Höjdpunkter",
        "event-prao-highlight-1": "Praktikliknande PRAO för elever i årskurs 8–9 att utforska programmering och teknik.",
        "event-prao-highlight-2": "Undervisning i små grupper med praktiska moment i Scratch och Python.",
        "event-prao-highlight-3": "Handleds av studenter och personal från Linnéuniversitetet.",
        "event-prao-highlight-4": "Fokus på att förstå grundläggande programmeringskoncept, problemlösning och digitalt tänk.",
        "event-prao-highlight-5": "Genomförs två gånger per termin med högst två elever per vecka.",
        "event-prao-overview-heading": "Översikt",
        "event-prao-overview-1": "PRAO-veckan (Praktisk arbetslivsorientering) ger elever i åk 8–9 chansen att upptäcka arbetslivet och få inblick i teknik och programmering på Linnéuniversitetet.",
        "event-prao-overview-2": "Under besöket deltar eleverna i strukturerade undervisningspass som förberetts av LNU-studenter och personal, där visuell programmering i Scratch kombineras med introducerande Python.",
        "event-prao-overview-3": "Målet är att introducera grundläggande datavetenskapskoncept, bygga självförtroende i problemlösning och visa hur studier eller jobb inom teknik kan se ut.",
        "event-prao-overview-4": "PRAO-veckor arrangeras två gånger per termin med två elever per vecka för en personlig lärmiljö.",
        "event-prao-activities-heading": "Aktiviteter & pass",
        "event-prao-activity-1": "Grunderna i Scratch som tränar sekvenser och händelsestyrt tänkande.",
        "event-prao-activity-2": "Ställa frågor och spara svar i Scratch-variabler.",
        "event-prao-activity-3": "Logiska jämförelser med heltalsvärden som styr besluten.",
        "event-prao-activity-4": "Använda if–else-satser för att utforska olika utfall.",
        "event-prao-activity-5": "Byta sprites och kostymer utifrån villkor för att visualisera logik.",
        "event-prao-activity-6": "Förstå hur kodens struktur leder till det beteende som syns på skärmen.",
        "event-prao-activity-7": "Vägledd övergång från Scratch-koncept till introducerande Python.",
        "event-prao-activity-8": "Diskussioner om skillnaden mellan strängar och heltal när elever arbetar med data.",
        "event-prao-activity-9": "Ta emot användarinmatning och spara den i Python-variabler.",
        "event-prao-activity-10": "Skriva ut och kombinera text med numeriska värden i Python-program.",
        "event-prao-activity-11": "Skriva enkla villkorssatser i Python med if/else.",
        "event-prao-activity-12": "Läsa och tolka grundläggande felmeddelanden tillsammans med handledare.",
        "event-prao-activity-13": "Introduktion till felsökningstekniker som hjälper elever att rätta misstag.",
        "event-prao-activity-14": "Varje pass inleds med en kort begreppsgenomgång följt av praktiskt arbete.",
        "event-prao-schedule-heading": "Viktiga platser",
        "event-prao-schedule-1": "Linnéuniversitetet, campus Växjö – undervisningslabb och lärmiljöer för introducerande programmeringsworkshops.",
        "event-prao-participation-heading": "Deltagande & resurser",
        "event-prao-participation-1": "PRAO-veckan riktar sig till elever i årskurs 8–9 som del av deras praktiska arbetslivsorientering.",
        "event-prao-participation-2": "Medverkan planeras tillsammans med skolorna och varje PRAO-period tar emot två elever för individanpassad handledning.",
        "event-february-programming-name": "Programmeringskurs för barn",
        "event-february-programming-datetime": "16–18 februari · 09.00–12.00 eller 13.00–16.00",
        "event-february-programming-location": "Plats: Lärlabb i Växjö",
        "event-february-programming-language": "Språk: Svenska (stöd på engelska)",
        "event-oppet-hus-vaxjo-name": "Öppet hus · Växjö",
        "event-oppet-hus-vaxjo-datetime": "26 februari · 09.00–15.00",
        "event-oppet-hus-vaxjo-location": "Plats: Campus Växjö",
        "event-oppet-hus-vaxjo-language": "Språk: Svenska (stöd på engelska)",
        "event-oppet-hus-kalmar-name": "Öppet hus · Kalmar",
        "event-oppet-hus-kalmar-datetime": "4 mars · 09.00–15.00",
        "event-oppet-hus-kalmar-location": "Plats: Campus Kalmar",
        "event-oppet-hus-kalmar-language": "Språk: Svenska (stöd på engelska)",
        "event-openhouse-kalmar-highlights-heading": "Höjdpunkter",
        "event-openhouse-kalmar-highlight-1": "Träffa universitetsanställda, studenter och studievägledare på campus Kalmar.",
        "event-openhouse-kalmar-highlight-2": "Utforska utbildningar via inspirationspass, informationstillfällen och praktiska aktiviteter.",
        "event-openhouse-kalmar-highlight-3": "Mässområde öppet hela dagen med möjlighet att få svar om studentliv, boende och antagning.",
        "event-openhouse-kalmar-highlight-4": "Rundvandringar och programvisningar pågår löpande över campus.",
        "event-openhouse-kalmar-overview-heading": "Översikt",
        "event-openhouse-kalmar-overview-1": "Den 4 mars 2026 välkomnar Linnéuniversitetet blivande studenter till Öppet hus på campus Kalmar.",
        "event-openhouse-kalmar-overview-2": "Besökare kan delta i föreläsningar, uppleva lärmiljöer, träffa nuvarande studenter och få svar på frågor om utbildningar och ansökan.",
        "event-openhouse-kalmar-overview-3": "Mässan är öppen 09.00–14.00 med inspirationspass, allmän info, guidningar och aktiviteter över hela campus.",
        "event-openhouse-kalmar-activities-heading": "Aktiviteter & sessioner",
        "event-openhouse-kalmar-activity-1": "Inspirationspass ledda av lärare, studenter och personal.",
        "event-openhouse-kalmar-activity-2": "Allmänna informationspass om studier vid LNU, antagning och campusservice.",
        "event-openhouse-kalmar-activity-3": "Guidade turer som visar Kalmars lärmiljöer, labb och programlokaler.",
        "event-openhouse-kalmar-activity-4": "Mässområde där besökare kan träffa representanter från olika institutioner och stödfunktioner.",
        "event-openhouse-kalmar-activity-5": "Möten med nuvarande studenter som delar erfarenheter av studentlivet i Kalmar.",
        "event-openhouse-kalmar-schedule-heading": "Viktiga platser",
        "event-openhouse-kalmar-schedule-1": "Campus Kalmar – mässyta, föreläsningssalar och startpunkter för guidningarna.",
        "event-openhouse-kalmar-schedule-2": "Olika fakultetsbyggnader och labb som visar upp sina utbildningar.",
        "event-openhouse-kalmar-participation-heading": "Deltagande & resurser",
        "event-openhouse-kalmar-participation-1": "Mer information och uppdateringar publiceras på evenemangets webbsida.",
        "event-openhouse-kalmar-participation-2": "Läs mer: https://lnu.se/mot-linneuniversitetet/aktuellt/kalender/2026/oppet-hus-kalmar/",
        "event-openhouse-highlights-heading": "Höjdpunkter",
        "event-openhouse-highlight-1": "Rekrytera framtida studenter genom inspirationspass och aktiviteter på mässan.",
        "event-openhouse-highlight-2": "Erbjud rundvandringar, öppna labb eller smakprov på föreläsningar som visar upp programmet.",
        "event-openhouse-highlight-3": "Planera för pass både på förmiddagen och eftermiddagen så att besökande skolor kan delta.",
        "event-openhouse-overview-heading": "Översikt",
        "event-openhouse-overview-1": "Öppet hus är ett perfekt tillfälle att rekrytera fler studenter till ditt program. Under dagarna finns möjlighet att synas genom att hålla inspirationspass och genom att delta som utställare på mässan. Du kan också anmäla en rundvandring eller en annan aktivitet – till exempel en visning av programmets lokaler, ett öppet labb eller en smakföreläsning.",
        "event-openhouse-overview-2": "Öppet hus är en av Linnéuniversitets största rekryteringsinsatser under läsåret, och under 2025 besökte närmare 2 500 personer oss på campus Växjö och campus Kalmar. Besökarna kommer främst från gymnasieskolor i Småland och Blekinge, men vi välkomnar även långväga gäster från övriga Sverige.",
        "event-openhouse-overview-3": "Sedan 2025 är Öppet hus ett gemensamt evenemang för båda våra campus, där projektgruppen strävar efter att erbjuda ett likvärdigt utbud oavsett om besökarna väljer Växjö eller Kalmar.",
        "event-openhouse-expectations-heading": "Olika sätt att delta",
        "event-openhouse-expectation-1": "Inspirationspassen ger dig möjlighet att berätta varför studenter ska välja ditt program. Passet kan ledas av till exempel programansvarig, studievägledare eller nuvarande studenter. Vi rekommenderar att involvera studenter eftersom de lättare kan beskriva vardagen som student. Varje pass är 20 minuter långt med utrymme för frågor.",
        "event-openhouse-expectation-2": "Mässan är ett tillfälle att föra kvalitativa samtal med presumtiva studenter. Det är också ett bra sätt att synliggöra din utbildning, även för besökare som inte går på ditt inspirationspass. Planera gärna någon aktivitet i montern för att locka fler besökare.",
        "event-openhouse-expectation-3": "Rundvandringar och aktiviteter låter dig visa upp en specifik studiemiljö eller en del av utbildningen. Det kan vara ett öppet labb, en visning av speciallokaler, en konsert med studenter eller en prova på-aktivitet. Kom gärna med egna idéer!",
        "event-openhouse-schedule-heading": "Schema för Öppet hus 2026",
        "event-openhouse-schedule-1": "Campus Växjö — torsdag 26 februari kl. 9.00–14.00",
        "event-openhouse-schedule-2": "Campus Kalmar — onsdag 4 mars kl. 9.00–14.00",
        "event-openhouse-schedule-3": "Varje inspirationspass bör erbjudas minst en gång på förmiddagen och en gång på eftermiddagen för att passa besökande skolor.",
        "event-openhouse-participation-heading": "Deltagande & anmälan",
        "event-openhouse-participation-1": "Anmälan för deltagande under Öppet hus 2026 är öppen från 1 september och stänger den 31 oktober.",
        "event-openhouse-participation-2": "Gör din anmälan här.",
        "event-openhouse-participation-3": "Har du frågor? Kontakta projektgruppen för Öppet hus på oppethus@lnu.se.",
        "event-openhouse-participation-4": "Se information som publicerats för externa besökare.",
        "event-igeday-name": "IGEDAY",
        "event-igeday-datetime": "20 mars · 09.00–15.00",
        "event-igeday-location": "Plats: Campus Växjö",
        "event-igeday-language": "Språk: Svenska (information på engelska finns · endast kvinnor)",
        "event-igeday-highlights-heading": "Höjdpunkter",
        "event-igeday-highlight-1": "Nationellt initiativ som introducerar tjejer och icke-binära ungdomar till ingenjörsyrket.",
        "event-igeday-highlight-2": "Deltagare 13–19 år får praktiska erfarenheter på riktiga ingenjörsarbetsplatser runt om i Sverige.",
        "event-igeday-highlight-3": "Alla organisationer med minst en kvinnlig ingenjör kan delta som värdföretag.",
        "event-igeday-highlight-4": "Arrangeras och stöttas av stiftelsen Womengineer.",
        "event-igeday-highlight-5": "Fokuserar på att ge unga mod att utforska ingenjörsyrket och välja sin framtid med självförtroende.",
        "event-igeday-overview-heading": "Översikt",
        "event-igeday-overview-1": "IGEday är ett rikstäckande evenemang där tjejer och icke-binära 13–19 år får utforska hur det är att arbeta som ingenjör medan företag över hela Sverige öppnar dörrarna för interaktiva pass, workshops och prova på-aktiviteter.",
        "event-igeday-overview-2": "Nästa IGEday äger rum den 20 mars 2026 och anmälan för deltagare öppnar den 7 januari.",
        "event-igeday-overview-3": "Initiativet vill inspirera unga att se ingenjörsyrket som en spännande och tillgänglig karriärväg, med återkommande värdar som Siemens Energy, E.ON och Tetra Pak.",
        "event-igeday-activities-heading": "Aktiviteter & pass",
        "event-igeday-activity-1": "Guidad rundtur på ingenjörsarbetsplatser som visar labb, kontrollrum och projektmiljöer.",
        "event-igeday-activity-2": "Praktiska problemlösningspass där deltagarna bygger prototyper, testar idéer och samarbetar med ingenjörer.",
        "event-igeday-activity-3": "Föreläsningar med ingenjörer och förebilder som delar studievägar, vardagsjobb och tips inför val av utbildning.",
        "event-igeday-activity-4": "Grupputmaningar, teamwork-aktiviteter och frågestunder om studier och karriärvägar.",
        "event-igeday-activity-5": "Lärare, mentorer och studie- och yrkesvägledare är välkomna att följa med grupperna och stötta upplevelsen.",
        "event-igeday-activity-6": "Inspirerande berättelser från kvinnliga ingenjörer och unga deltagare som visar olika framtidsvägar inom teknik.",
        "event-igeday-schedule-heading": "Viktiga datum & värduppdateringar",
        "event-igeday-schedule-1": "Företag med minst en kvinnlig ingenjör kan delta som värd och anmälan för IGEday 2026 stänger den 30 november.",
        "event-igeday-schedule-2": "Anmälan för deltagare öppnar den 7 januari och listan över medverkande företag uppdateras löpande på https://igeday.com så att sökande kan välja önskad arbetsplats.",
        "event-igeday-schedule-3": "Den 20 mars 2026 genomför värdar över hela Sverige morgonpass eller heldagsprogram, från fabriksbesök till innovationsworkshops.",
        "event-igeday-participation-heading": "Deltagande & resurser",
        "event-igeday-participation-1": "Alla 13–19-åringar som identifierar sig som tjejer eller icke-binära kan anmäla sig individuellt eller med sin skolgrupp.",
        "event-igeday-participation-2": "Värdar behöver minst en kvinnlig ingenjör och kan skapa rundvandringar, workshops eller labbpass som speglar deras arbetsplats och team.",
        "event-igeday-participation-3": "Tidigare deltagare berättar: \"Det bästa var att höra hur ingenjörsyrket faktiskt är.\", \"Roligast var att lösa uppgifter tillsammans.\" och \"Jag fick se hur min framtida arbetsplats kan se ut!\"",
        "event-igeday-participation-4": "IGEday arrangeras av stiftelsen Womengineer som vill att Sverige ska examinera lika många kvinnliga som manliga ingenjörer till 2030 och stöttar globala mål 4, 5 och 10.",
        "event-igeday-participation-5": "Initiativet blir verklighet tack vare partners, skolor, företag och volontärer i hela Sverige som samordnar logistik och mentorskap.",
        "event-igeday-participation-6": "Mer information, vanliga frågor och inspiration från tidigare år finns på den officiella webbplatsen: https://igeday.com.",
        "event-march-programming-name": "Programmeringskurs för barn",
        "event-march-programming-datetime": "30 mars–1 april · 09.00–12.00 eller 13.00–16.00",
        "event-march-programming-location": "Plats: Lärlabb i Växjö",
        "event-march-programming-language": "Språk: Svenska (stöd på engelska)",
        "event-science-linne-name": "Science Linné",
        "event-science-linne-datetime": "24–25 april",
        "event-science-linne-location": "Plats: Campus Växjö",
        "event-science-linne-language": "Språk: Svenska (information på engelska finns)",
        "event-science-linne-highlights-heading": "Höjdpunkter",
        "event-science-linne-highlight-1": "Årlig teknik- och vetenskapsfestival med över 1 000 besökare.",
        "event-science-linne-highlight-2": "Praktiska experiment, demonstrationer och utmaningar för elever och allmänhet.",
        "event-science-linne-highlight-3": "Utställare från Linnéuniversitetet och regionala teknikföretag.",
        "event-science-linne-highlight-4": "Aktiviteter inom LEGO-engineering, robotik, biologi, VR och hållfasthetslära.",
        "event-science-linne-highlight-5": "Skapar intresse för teknik, naturvetenskap och matematik hos barn och unga.",
        "event-science-linne-overview-heading": "Översikt",
        "event-science-linne-overview-1": "Science City förvandlar campus Växjö till en miljö fylld av teknik, vetenskap och spänning.",
        "event-science-linne-overview-2": "Över 1 000 nyfikna besökare testade interaktiva stationer, live-demo och kreativa utmaningar.",
        "event-science-linne-overview-3": "Utställare från LNU och regionala företag visade allt från robotik till miljövetenskap.",
        "event-science-linne-activities-heading": "Aktiviteter & stationer",
        "event-science-linne-activity-1": "Fullskalig LEGO Volvo V70 utställd av David Gustafsson, vinnare av LEGO Masters Sverige.",
        "event-science-linne-activity-2": "Ingenjörsutmaningar: katapultbygge, 3D-flygplan i VR och test av radiostyrda bilar.",
        "event-science-linne-activity-3": "Kreativt skapande: svarva trääpplen, bygga konstruktioner och testa matte-trolleri.",
        "event-science-linne-activity-4": "Science stationer: studera alger i mikroskop och prova smoothies gjorda på alger.",
        "event-science-linne-activity-5": "Teknikvisningar: industrirobotar, studentbyggda dansmattor och VR-upplevelser.",
        "event-science-linne-activity-6": "“Starkast vinner!” – populär brobyggartävling där vinnaren höll över 40 kilo.",
        "event-science-linne-activity-7": "Förmiddag förbokade grupper i årskurs 5–9, eftermiddag öppen för gymnasiet och allmänheten.",
        "event-science-linne-partners-heading": "Partners & medverkande",
        "event-science-linne-partners-1": "Arrangeras av Linnéuniversitetet tillsammans med Epic och sponsras av Teknikcollege och Växjö kommun.",
        "event-science-linne-partners-2": "Genomförs med hjälp av universitetsanställda, studentvolontärer och regionala teknikföretag.",
        "event-science-linne-partners-3": "Projektledarna Laure Fournier och Katrin Lindwall betonar vikten av att inspirera unga med teknikstudier.",
        "event-science-linne-locations-heading": "Viktiga platser",
        "event-science-linne-location-1": "Campus Växjö – flera byggnader och öppna ytor rymmer montrar, workshops och demo.",
        "event-science-linne-participation-heading": "Deltagande & resurser",
        "event-science-linne-participation-1": "Mer info och bilder: https://lnu.se/mot-linneuniversitetet/aktuellt/nyheter/2023/dricka-alger-bygga-broar-och-svarva-applen--science-city-gav-manga-smakprov-for-den-teknikintresserade/",
        "event-june-programming-name": "Programmeringskurs för barn",
        "event-june-programming-datetime": "15–17 juni · 09.00–12.00 eller 13.00–16.00",
        "event-june-programming-location": "Plats: Lärlabb i Växjö",
        "event-june-programming-language": "Språk: Svenska (stöd på engelska)",
        "faq-title": "Vanliga frågor",
        "faq1-question": "Vilka kan delta i Tutorial Education Program?",
        "faq1-answer": "Kandidatstudenter från och med år två samt masterstudenter inskrivna på Datavetenskap eller Medieteknik vid LNU.",
        "faq2-question": "Behöver jag tidigare undervisningserfarenhet?",
        "faq2-answer": "Nej. Vi erbjuder mentorskap, introduktionsworkshops och resurser som gör att du känner dig trygg i rollen.",
        "faq3-question": "Hur mycket tid måste jag lägga?",
        "faq3-answer": "Du kan arbeta deltid på 25% eller 50% beroende på studietakt och tillgänglighet. Vi planerar aktiviteterna så att de fungerar med dina studier.",
        "faq4-question": "Vilka typer av projekt får jag arbeta med?",
        "faq4-answer": "Uppdragen spänner från labbhandledning och forskningsstöd till workshops, kodklubbar och andra outreach-aktiviteter.",
    }
};

// Function to get a cookie
function getCookie(name) {
    const cookies = document.cookie.split("; ");
    for (const cookie of cookies) {
        const [key, value] = cookie.split("=");
        if (key === name) {
            return value;
        }
    }
    return null;
}

// Function to set a cookie
function setCookie(name, value, days) {
    const date = new Date();
    date.setTime(date.getTime() + days * 24 * 60 * 60 * 1000);
    document.cookie = `${name}=${value}; expires=${date.toUTCString()}; path=/; SameSite=Lax`;
}

// Load the saved language as early as possible
function loadSavedLanguage() {
    const savedLanguage = getCookie("selectedLanguage") || "en";
    document.documentElement.lang = savedLanguage; // Set language at document level immediately
}

function changeLanguage(language) {
    document.documentElement.lang = language;
    setCookie("selectedLanguage", language, 30); // Save language preference

    const elements = document.querySelectorAll("[data-lang]");
    elements.forEach((el) => {
        const key = el.getAttribute("data-lang");
        const newText = translations[language][key];

        // only update if the text is different
        if (newText && el.textContent !== newText) {
            el.textContent = newText;
        }
    });

    updateLanguageButtons(language);

    window.dispatchEvent(new CustomEvent("languagechange", {
        detail: { language }
    }));
}

function updateLanguageButtons(language) {
    const buttons = document.querySelectorAll(".language-button");

    if (!buttons.length) {
        return;
    }

    buttons.forEach((button) => {
        const isActive = button.dataset.language === language;
        button.classList.toggle("is-active", isActive);
        button.setAttribute("aria-pressed", isActive ? "true" : "false");
    });
}

// Attach language toggle event
function attachLanguageToggle() {
    const buttons = document.querySelectorAll(".language-button");

    if (!buttons.length) {
        console.error("Language toggle buttons not found.");
        return;
    }

    // Ensure correct default state once buttons exist in the DOM
    updateLanguageButtons(document.documentElement.lang || "en");

    buttons.forEach((button) => {
        button.addEventListener("click", (e) => {
            e.preventDefault();
            const selectedLanguage = button.dataset.language;
            if (selectedLanguage) {
                changeLanguage(selectedLanguage);
            }
        });
    });
}

loadSavedLanguage(); // first apply the cookie to set the document language
changeLanguage(document.documentElement.lang); // then apply the language to the document right away
// then set it up so that once the DOM is loaded, the language toggle button gets its functioanlity
document.addEventListener("DOMContentLoaded", function () {
    attachLanguageToggle(); 
});
